name: API Tests with Pytest

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v1
    - name: Set up Python 3.11
      uses: actions/setup-python@v1
      with:
        python-version: 3.11
    - name: Install dependencies
      run: |
        pip install pipenv
        pipenv shell

    - name: Test with pytest
      run: |
        pytest
        
    - uses: actions/upload-artifact@v3
      if: ${{ always() }}
      with:
        name: test-artifacts
        path: result.xml    
