name: API Tests with Pytest

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2
    - name: Set up Python 3.11
      uses: actions/setup-python@v2
      with:
        python-version: 3.11
    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        pip install pytest
        if [ -f requirements.txt ]; then pip install -r requirements.txt; fi
        pip install pipenv
        pipenv install

    - name: Test  API with pytest
      run: |
        pipenv run python -m pytest

    - name: Test Performance of API with pytest and locust
      run: |
        pipenv run python Tests/api_performance/runner.py
        
    - uses: actions/upload-artifact@v3
      if: ${{ always() }}
      with:
        name: test-artifacts
        path: |
          Reports/report.html
          Logs/pytest.
          !Tests/api_performance/report/*.csv


#  report:
#    if: ${{ always() }}
#    needs: [ build ]
#    name: Add 3 and 7
#    runs-on: ubuntu-latest
#    steps:
#      - shell: bash
#        run: |
#          expr 3 + 7 > math-homework.txt
#      - name: Upload math result for job 1
#        uses: actions/upload-artifact@v3
#        with:
#          name: homework
#          path: math-homework.txt
